linters:
  disable-all: true
  enable:
    - vet
    - goimports
    - misspell
    - goconst
    - golint
    - errcheck
#    - gosec
#    - unconvert
#    - staticcheck
#    - varcheck
#    - structcheck
#    - deadcode
#    - scopelint


issues:
  exclude:
    - "func name will be used as test\\.Test.* by other packages, and that stutters; consider calling this"
    - "Potential file inclusion via variable"
    - "should have( a package)? comment"

  exclude-use-default: false
  exclude-rules:
    - path: "fsm_test.go"
      linters:
        - govet
    - path: "lib/statemachine/group.go"
      linters:
        - golint
    - path: "sector_states.go"
      linters:
        - golint
    - path: "lib/statemachine/machine.go"
      linters:
        - golint
    - path: "lib/statemachine/machine_test.go"
      linters:
        - errcheck
    - path: node/modules/lp2p
      linters:
        - golint
    - path: ".*_test.go"
      linters:
        - gosec

linters-settings:
  goconst:
    min-occurrences: 6
